# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura')),
                ('tempo', models.TimeField(verbose_name='Temperatura')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Materiais',
                'verbose_name': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura')),
            ],
            options={
                'verbose_name_plural': 'Temperaturas',
                'verbose_name': 'Temperatura',
            },
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField(verbose_name='Temperatura')),
            ],
            options={
                'verbose_name_plural': 'Tempos',
                'verbose_name': 'Tempo',
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Tipo de Materiais',
                'verbose_name': 'Tipo de Material',
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(max_length=50, verbose_name='Tipo do Material')),
                ('grupo', models.CharField(max_length=8, verbose_name='Número do Grupo')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Processo Finalizado')),
                ('timestamp', models.DateField(blank=True, null=True, verbose_name='Hora de Início do Tratamento')),
                ('temperatura_tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamento.Temperatura', verbose_name='Temperatura Máxima')),
                ('tempo_tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamento.Tempo', verbose_name='Tempo de Tratamento')),
            ],
            options={
                'verbose_name_plural': 'Tratamento de Materiais',
                'verbose_name': 'Tratamento de Material',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='tipo_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamento.TipoMaterial', verbose_name='Tipo de Material'),
        ),
        migrations.AddField(
            model_name='grafico',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamento.Tratamento', verbose_name='Tratamento'),
        ),
    ]
