# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AlterModelOptions(
            name='tipomaterial',
            options={'verbose_name': 'Tipo de Material', 'verbose_name_plural': 'Tipo de Materiais'},
        ),
        migrations.AlterModelOptions(
            name='tratamento',
            options={'verbose_name': 'Tratamento de Material', 'verbose_name_plural': 'Tratamento de Materiais'},
        ),
    ]
