# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0002_auto_20161116_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=50, verbose_name='Temperatura')),
            ],
            options={
                'verbose_name_plural': 'Temperaturas',
                'verbose_name': 'Temperatura',
            },
        ),
        migrations.AddField(
            model_name='tratamento',
            name='temperatura',
            field=models.CharField(default=0, max_length=50, verbose_name='Temperatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafico',
            name='temperatura',
            field=models.ManyToManyField(related_name='temperatura_set', to='tratamento.Temperatura'),
        ),
        migrations.AddField(
            model_name='grafico',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamento.Tratamento', verbose_name='Tratamento'),
        ),
    ]
