# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0004_auto_20161116_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura'),
        ),
    ]
