# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0005_auto_20161116_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturas', models.ManyToManyField(related_name='temperatura_set', to='tratamento.Temperatura')),
                ('tempos', models.ManyToManyField(related_name='tempo_set', to='tratamento.Tempo')),
            ],
        ),
        migrations.RemoveField(
            model_name='tratamento',
            name='temperaturas',
        ),
        migrations.RemoveField(
            model_name='tratamento',
            name='tempos',
        ),
        migrations.AddField(
            model_name='grafico',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamento.Tratamento', verbose_name='Tratamento'),
        ),
    ]
