# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0006_auto_20161116_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Processo Finalizado'),
        ),
    ]
