# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0007_tratamento_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='timestamp',
            field=models.DateField(blank=True, null=True, verbose_name='Hora de Início do Tratamento'),
        ),
    ]
