# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0008_tratamento_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafico',
            name='temperaturas',
        ),
        migrations.RemoveField(
            model_name='grafico',
            name='tempos',
        ),
        migrations.AddField(
            model_name='grafico',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Temperatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grafico',
            name='tempo',
            field=models.TimeField(default='00:00', verbose_name='Temperatura'),
            preserve_default=False,
        ),
    ]
